---
- name: Install Mongo
  hosts: db
  become: true
  gather_facts: no
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Add repo key
      apt_key:
        id: "0xd68fa50fea312927"
        keyserver: keyserver.ubuntu.com
        state: present

    - name: add repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        filename: mongodb-org-3.2
        update_cache: yes

    - name: Install mongodb
      apt:
        name: mongodb-org
        state: latest

    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644

    - name: Enable and start mongo
      systemd:
        name: mongod
        state: started
        enabled: yes
